### ISSUE TITLE
Lots of memory reallocation and copying in website generator.

### ISSUE THREAD

**Issue by everslick** [dsyleixa/Arduino#1]
https://github.com/dsyleixa/Arduino/blob/4139cefcd91f37533e6a90b673577c216930694b/ESP32_ServerHomeWebMail_089a/ESP32_ServerHomeWebMail_089a.ino#L1606

Here you create a new String object and then start to fill it with data. The point is, each time you append data with `+=` the memory held by script, will be reallocated and the old content will be copied into the new memory, this results in hundreds of reallocations and calls to memcpy. I think it should take some time to load the page, no?

The simple solution is to reserve the expected amount of memory needed to hold **all** of the HTML code, before you start filling it. just do `script.reserve(EXPECTED_MAX_MEM);` where EXPECTED_MAX_MEM is the page size in bytes. You can look at the page source code and measure how big the output is and then add a small percentage for safety.

I bet the page loads measurable faster then.

**Comment by dsyleixa** [comment]
yes I know, but that is not crucial and loading the site is quick enough, even formerly for esp8266. Perhaps I might change it some day when I once will get the website to build at all by ESP32.

**Comment by dsyleixa** [comment]
yes I know, but that is not crucial and loading the site is quick enough, even formerly for esp8266. Perhaps I might change it some day when I once will get the website to build at all by ESP32. Currently only the esp8266 version is running fine, and it all fails for esp32.

**Comment by everslick** [comment]
hmm, this is not dependent on the platform it is running on, and even, if it feels like it is loading fast enough, it is just ONE line of code to add. It's just best practice doing so. And more: not doing it, might lead to crashes or wrong HTML code, because you never check, if the String object is still valid. Even more as you do not create your strings in flash (with the `F()` and `PSTR()` macros (only relevant for ESP8266, but you can leave the macros in on ESP32). So you already waste some RAM here. If the ESP8266 is struggling, I would start to optimize a little at those easy wins. Otherwise it might start to fail at some random time later, if you change something in an seemingly unrelated part of the code. this can become really, really tricky to debug. just my 2 cents.

Don't read this as critique, it is just some well meant advise.

**Comment by dsyleixa** [comment]
thanks, I appreciate it, but first I want it to run without issues, and then I'll perhaps change it, both for esp8266 and 32.

**Comment by dsyleixa** [comment]
thanks, I appreciate it, but first I want it to run without issues, and then I'll perhaps change it, both for esp8266 and 32.
("never turn 2 knobs at the same time" ;) )

**Comment by dsyleixa** [comment]
BTW: I haven't the slightest idea how many mems this thing needs, tbh....

**Comment by everslick** [comment]
Log `script.length()` before you send the page.

**Comment by dsyleixa** [comment]
ok, will do.
Any hints to run the sites by esp32 correctly?
tbh, absolutely annoying that esp8266 and esp32 APIs ae not compatible, that would never happen to any original Arduino boards!
Current ESP32 version but still no html websites:
https://github.com/dsyleixa/Arduino/tree/master/ESP32_IoT/ESP32_ServerHomeWebMail_089b

**Comment by dsyleixa** [comment]
@everslick:
I meanwhile found a Serial  error message when my html website tries to build up - what does that mean?

`Guru Meditation Error: Core  1 panic'ed (LoadProhibited). `

I never get this message by my esp8266!
```

New Client.
GET / HTTP/1.1
Host: mySmartHome.sytes.net:8008
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
DNT: 1
Connection: keep-alive
Upgrade-Insecure-Requests: 1
Cache-Control: max-age=0

Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x400013f9  PS      : 0x00060c30  A0      : 0x800d7aac  A1      : 0x3ffb19a0  
A2      : 0x3ffbdbb8  A3      : 0x00000000  A4      : 0x000000ff  A5      : 0x0000ff00  
A6      : 0x00ff0000  A7      : 0xff000000  A8      : 0x00000000  A9      : 0x3ffb1970  
A10     : 0x3ffbdbb8  A11     : 0x3f400176  A12     : 0x000000ff  A13     : 0x0000ff00  
A14     : 0x00ff0000  A15     : 0xff000000  SAR     : 0x00000010  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000000  LBEG    : 0x400013f9  LEND    : 0x4000140d  LCOUNT  : 0xffffffff  

ELF file SHA256: 0000000000000000

Backtrace: 0x400013f9:0x3ffb19a0 0x400d7aa9:0x3ffb19b0 0x400d8a48:0x3ffb1f80 0x400e2765:0x3ffb1fb0 0x4008a02e:0x3ffb1fd0

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5856
entry 0x400806a8

```

**Comment by dsyleixa** [comment]
@everslick:
all the Strings are processed fine on my esp8266 so I actually doubt that faulty Strings may occur on my ESP32 then.

But I meanwhile found a Serial  error message when my html website tries to build up - what does that mean?

`Guru Meditation Error: Core  1 panic'ed (LoadProhibited). `

I never get this message by my esp8266!

OTOH, when I cut down my code to just 1/10 of the original html code then it runs ok!

```

New Client.
GET / HTTP/1.1
Host: mySmartHome.sytes.net:8008
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
DNT: 1
Connection: keep-alive
Upgrade-Insecure-Requests: 1
Cache-Control: max-age=0

Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x400013f9  PS      : 0x00060c30  A0      : 0x800d7aac  A1      : 0x3ffb19a0  
A2      : 0x3ffbdbb8  A3      : 0x00000000  A4      : 0x000000ff  A5      : 0x0000ff00  
A6      : 0x00ff0000  A7      : 0xff000000  A8      : 0x00000000  A9      : 0x3ffb1970  
A10     : 0x3ffbdbb8  A11     : 0x3f400176  A12     : 0x000000ff  A13     : 0x0000ff00  
A14     : 0x00ff0000  A15     : 0xff000000  SAR     : 0x00000010  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000000  LBEG    : 0x400013f9  LEND    : 0x4000140d  LCOUNT  : 0xffffffff  

ELF file SHA256: 0000000000000000

Backtrace: 0x400013f9:0x3ffb19a0 0x400d7aa9:0x3ffb19b0 0x400d8a48:0x3ffb1f80 0x400e2765:0x3ffb1fb0 0x4008a02e:0x3ffb1fd0

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5856
entry 0x400806a8


.....
WiFi connected: 192.168.2.1
192.168.2.202
8008
WiFi Server started
Web Server started
Use this URL to connect: http://192.168.2.202:8008/
http://mySmartHome.sytes.net:8008/
  NTP TimeServer started!
Date & Time:  
Sun 08 Oct 2023 10:46:45 
setup done 

10:46:46   Sun 08 Oct 2023
Client sensors:
 c0_t1=-- c0_h1=-- c0_t2=-- c0_h2=-- 
 c1_t1=-- c1_h1=-- c1_t2=-- c1_h2=-- 
 c2_t1=-- c2_h1=-- c2_t2=-- c2_h2=-- 
 c3_t1=-- c3_h1=-- c3_t2=-- c3_h2=-- 


```

PS, 
meanwhile could rework my esp8266 code to port it to esp32, e.g. also my log-in function.

**Comment by everslick** [comment]
1. That is good news, it means you have got the webserver working fine.
2. the crash is due to a bug in your code. It happens often that porting a codebase to another platform reveals subtle bugs.
3. You can decode the stacktrace with something like the stackdecoder you can google that or you can add more and more lines of code until you find the one that crashes.
4. don't give up, you are pretty close!

**Comment by dsyleixa** [comment]
again, thank you very much!
Now as i am already reworking the entire code to port it to ESP32 then I can eventually also add your feature 
`script.reserve(EXPECTED_MAX_MEM);`
here ...?

But where do I have to put this line here...?
```

WiFiClient client = wifiserver.available();   // listen for incoming clients

   //if(!client) return;  // <<<<<<<< needed?

   if (client) {                               // if you get a client,
      Serial.println("New Client.");           // print a message out the serial port
      String currentLine = "";                 // make a String to hold incoming data from the client

      while (client.connected()) {             // loop while the client's connected
         if (client.available()) {             // if there's bytes to read from the client,
            char c = client.read();            // read a byte, then
            Serial.write(c);                   // print it out the serial monitor
            if (c == '\n') {                   // if the byte is a newline character

               // if the current line is blank, you got two newline characters in a row.
               // that's the end of the client HTTP request, so send a response:
               if (currentLine.length() == 0) {
                  // HTTP headers always start with a response code (e.g. HTTP/1.1 200 OK)
                  // and a content-type so the client knows what's coming, then a blank line:                  

                  // init website

                  script += ("HTTP/1.1 200 OK \n");
                  script += ("Content-Type: text/html \n");
                  // ***SNIP***
      
```

**Comment by everslick** [comment]
Right after `String script;`

**Comment by dsyleixa** [comment]
update,
size was printed as 9500 bytes, now I took script.reserve(12000) for further future extensions, and this main website  works fine!
Again, thanks a lot!
8-)

**Comment by dsyleixa** [comment]
closing issue as has been solved!
