### ISSUE TITLE
Return pointer to buffer on stack

### ISSUE THREAD

**Issue by everslick** [dsyleixa/Arduino#2]
https://github.com/dsyleixa/Arduino/blob/5f5aef2c11b79d263ff6f3891552aed32082c38a/ESP32_IoT/ESP32_ServerHomeWebMail_089b/ESP32_ServerHomeWebMail_089b.ino#L539

Here you return a pointer to a stack variable. This is not allowed. After the function returns the stack is unwind and accessing that location in memory is illegal. This is most likely your bug you are experiencing. Please note it is a bug on ESP8266 too, you just have been lucky.

Change the function to return a String and it works.

**Comment by dsyleixa** [comment]
awesome, thank you very much, now the actual website works!

Now there is just 1 issue left as to the "handleNotAuthorized" login-website... 8-)

**Comment by everslick** [comment]
glad to hear that! closing issue as fixed then!
